// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// process_attr_col_rcpp
List process_attr_col_rcpp(std::vector<std::string> x);
RcppExport SEXP _igsc_process_attr_col_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(process_attr_col_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// processStrings
std::vector<std::string> processStrings(std::vector<std::string> x);
RcppExport SEXP _igsc_processStrings(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(processStrings(x));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_rcpp
std::vector<std::string> revcomp_rcpp(std::vector<std::string> dna_strings);
RcppExport SEXP _igsc_revcomp_rcpp(SEXP dna_stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dna_strings(dna_stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_rcpp(dna_strings));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_rcpp2
std::vector<std::string> revcomp_rcpp2(std::vector<std::string> dna_strings, std::string mode);
RcppExport SEXP _igsc_revcomp_rcpp2(SEXP dna_stringsSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dna_strings(dna_stringsSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_rcpp2(dna_strings, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_igsc_process_attr_col_rcpp", (DL_FUNC) &_igsc_process_attr_col_rcpp, 1},
    {"_igsc_processStrings", (DL_FUNC) &_igsc_processStrings, 1},
    {"_igsc_revcomp_rcpp", (DL_FUNC) &_igsc_revcomp_rcpp, 1},
    {"_igsc_revcomp_rcpp2", (DL_FUNC) &_igsc_revcomp_rcpp2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_igsc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
