// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compare_nonref_cpp
DataFrame compare_nonref_cpp(DataFrame df, std::string ref, std::string pos_col, std::string seq_col, std::string name_col, std::string match_symbol, std::string mismatch_symbol, bool keep_gaps, std::string nonref_mismatch_as);
RcppExport SEXP _igsc_compare_nonref_cpp(SEXP dfSEXP, SEXP refSEXP, SEXP pos_colSEXP, SEXP seq_colSEXP, SEXP name_colSEXP, SEXP match_symbolSEXP, SEXP mismatch_symbolSEXP, SEXP keep_gapsSEXP, SEXP nonref_mismatch_asSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< std::string >::type ref(refSEXP);
    Rcpp::traits::input_parameter< std::string >::type pos_col(pos_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type seq_col(seq_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type name_col(name_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type match_symbol(match_symbolSEXP);
    Rcpp::traits::input_parameter< std::string >::type mismatch_symbol(mismatch_symbolSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_gaps(keep_gapsSEXP);
    Rcpp::traits::input_parameter< std::string >::type nonref_mismatch_as(nonref_mismatch_asSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_nonref_cpp(df, ref, pos_col, seq_col, name_col, match_symbol, mismatch_symbol, keep_gaps, nonref_mismatch_as));
    return rcpp_result_gen;
END_RCPP
}
// mutate_value_cpp
CharacterVector mutate_value_cpp(CharacterVector value, CharacterVector ref_col, std::string match_symbol, std::string mismatch_symbol, bool keep_match_gaps, std::string nonref_mismatch_as);
RcppExport SEXP _igsc_mutate_value_cpp(SEXP valueSEXP, SEXP ref_colSEXP, SEXP match_symbolSEXP, SEXP mismatch_symbolSEXP, SEXP keep_match_gapsSEXP, SEXP nonref_mismatch_asSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type value(valueSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ref_col(ref_colSEXP);
    Rcpp::traits::input_parameter< std::string >::type match_symbol(match_symbolSEXP);
    Rcpp::traits::input_parameter< std::string >::type mismatch_symbol(mismatch_symbolSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_match_gaps(keep_match_gapsSEXP);
    Rcpp::traits::input_parameter< std::string >::type nonref_mismatch_as(nonref_mismatch_asSEXP);
    rcpp_result_gen = Rcpp::wrap(mutate_value_cpp(value, ref_col, match_symbol, mismatch_symbol, keep_match_gaps, nonref_mismatch_as));
    return rcpp_result_gen;
END_RCPP
}
// process_attr_col_rcpp
List process_attr_col_rcpp(std::vector<std::string> x);
RcppExport SEXP _igsc_process_attr_col_rcpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(process_attr_col_rcpp(x));
    return rcpp_result_gen;
END_RCPP
}
// processStrings
std::vector<std::string> processStrings(std::vector<std::string> x);
RcppExport SEXP _igsc_processStrings(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(processStrings(x));
    return rcpp_result_gen;
END_RCPP
}
// qual_stats_cpp
List qual_stats_cpp(List pq);
RcppExport SEXP _igsc_qual_stats_cpp(SEXP pqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pq(pqSEXP);
    rcpp_result_gen = Rcpp::wrap(qual_stats_cpp(pq));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_rcpp
std::vector<std::string> revcomp_rcpp(std::vector<std::string> dna_strings);
RcppExport SEXP _igsc_revcomp_rcpp(SEXP dna_stringsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dna_strings(dna_stringsSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_rcpp(dna_strings));
    return rcpp_result_gen;
END_RCPP
}
// revcomp_rcpp2
std::vector<std::string> revcomp_rcpp2(std::vector<std::string> dna_strings, std::string mode);
RcppExport SEXP _igsc_revcomp_rcpp2(SEXP dna_stringsSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type dna_strings(dna_stringsSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(revcomp_rcpp2(dna_strings, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_igsc_compare_nonref_cpp", (DL_FUNC) &_igsc_compare_nonref_cpp, 9},
    {"_igsc_mutate_value_cpp", (DL_FUNC) &_igsc_mutate_value_cpp, 6},
    {"_igsc_process_attr_col_rcpp", (DL_FUNC) &_igsc_process_attr_col_rcpp, 1},
    {"_igsc_processStrings", (DL_FUNC) &_igsc_processStrings, 1},
    {"_igsc_qual_stats_cpp", (DL_FUNC) &_igsc_qual_stats_cpp, 1},
    {"_igsc_revcomp_rcpp", (DL_FUNC) &_igsc_revcomp_rcpp, 1},
    {"_igsc_revcomp_rcpp2", (DL_FUNC) &_igsc_revcomp_rcpp2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_igsc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
