# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compare_nonref_cpp <- function(df, ref, pos_col = "position", seq_col = "seq", name_col = "seq.name", match_symbol = ".", mismatch_symbol = "x", keep_gaps = TRUE, nonref_mismatch_as = "base") {
    .Call(`_igsc_compare_nonref_cpp`, df, ref, pos_col, seq_col, name_col, match_symbol, mismatch_symbol, keep_gaps, nonref_mismatch_as)
}

mutate_value_cpp <- function(value, ref_col, match_symbol, mismatch_symbol, keep_match_gaps, nonref_mismatch_as) {
    .Call(`_igsc_mutate_value_cpp`, value, ref_col, match_symbol, mismatch_symbol, keep_match_gaps, nonref_mismatch_as)
}

process_attr_col_rcpp <- function(x) {
    .Call(`_igsc_process_attr_col_rcpp`, x)
}

processStrings <- function(x) {
    .Call(`_igsc_processStrings`, x)
}

qual_stats_cpp <- function(pq) {
    .Call(`_igsc_qual_stats_cpp`, pq)
}

revcomp_rcpp <- function(dna_strings) {
    .Call(`_igsc_revcomp_rcpp`, dna_strings)
}

revcomp_rcpp2 <- function(dna_strings, mode = "both") {
    .Call(`_igsc_revcomp_rcpp2`, dna_strings, mode)
}

